routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/clear', 'Shop\BasketController@clear');

Route::get('/', 'Shop\MainController@index')->name('shop.index');
Route::get('/product/{product}/show', 'Shop\MainController@show')->name('shop.product.show');

Route::get('/categories', 'Shop\MainController@categories')->name('shop.categories');
Route::get('/category/{category}', 'Shop\MainController@category')->name('shop.category');

Route::get('/filtered', 'Shop\MainController@filter')->name('shop.filter');

Route::group(['middleware' => 'auth'], function (){
    Route::get('/orders', 'Shop\OrderController@index')->name('shop.user.orders');
    Route::post('/product/{product}/rating', 'Shop\RatingController@add')->name('shop.product.rating.add');
});

Route::group(['prefix' => 'basket'], function (){

    Route::get('/', 'Shop\BasketController@index')->name('basket.index');
    Route::post('/{product}/add', 'Shop\BasketController@add')->name('basket.add');
    Route::delete('/{product}/delete', 'Shop\BasketController@delete')->name('basket.delete');

   Route::group(['middleware' => 'order'], function (){
        Route::get('/confirm', 'Shop\BasketController@confirm')->name('basket.confirm');
        Route::put('/processing', 'Shop\BasketController@processing')->name('basket.processing');
   });
});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']],function (){
    Route::get('/', 'Admin\HomeController@index')->name('admin.index');

    Route::get('/orders', 'Admin\OrderController@index')->name('admin.orders');

    Route::group(['prefix' => 'order'], function (){
        Route::get('/{order}', 'Admin\OrderController@show')->name('admin.order');
        Route::get('/{order}/edit', 'Admin\OrderController@edit')->name('admin.order.edit');
        Route::put('/{order}/update', 'Admin\OrderController@update')->name('admin.order.update');
    });

    Route::group(['prefix' => 'users'], function (){
        Route::get('/', 'Admin\UserController@index')->name('admin.users');
        Route::put('/{user}/update', 'Admin\UserController@update')->name('admin.user.update');
        Route::delete('/{user}/destroy', 'Admin\UserController@destroy')->name('admin.user.destroy');
    });

    Route::get('/statistics', 'Admin\StatisticController@index')->name('admin.statistic');

    Route::group(['prefix' => 'product'], function (){
        Route::resource('/label', 'Admin\Product\LabelController')->names('admin.label');
        Route::resource('/category', 'Admin\Product\CategoryController')->names('admin.category');
        Route::resource('/product', 'Admin\Product\ProductController')->names('admin.product');
    });
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/Product/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CategoryRequest;
use App\Models\Rest\Category;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    public function index(){
        $categories = Category::paginate(10);
        return view('admin.product.category.index', compact('categories'));
    }

    public function create(){
        return view('admin.product.category.create');

    }

    public function store(CategoryRequest $request){
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/category');
        }
        Category::create($params);
        session()->flash('success', 'Категория была добавлена');
        return redirect()->route('admin.category.create');
    }

    public function edit(Category $category){
        return view('admin.product.category.create', compact('category'));
    }

    public function update(CategoryRequest $request, Category $category){
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/category');
        }
        $category->update($params);
        session()->flash('warning', 'Категория была обновлена');
        return redirect()->route('admin.category.index');
    }

    public function destroy(Category $category){
        Storage::delete($category->image);
        $category->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/LabelController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\LabelRequest;
use App\Models\Rest\Label;

class LabelController extends Controller
{
    public function index(){
        $labels = Label::paginate(10);
        return view('admin.product.label.index', compact('labels'));
    }

    public function create(){
        return view('admin.product.label.create');
    }

    public function store(LabelRequest $request){
        Label::create($request->all());
        session()->flash('success', 'Лейбл был добавлен');
        return redirect()->route('admin.label.create');
    }

    public function edit(Label $label){
        return view('admin.product.label.create', compact('label'));
    }

    public function update(LabelRequest $request, Label $label){
        $label->update($request->all());
        session()->flash('warning', 'Лейбл был изменен');
        return redirect()->route('admin.label.index');
    }

    public function destroy(Label $label){
        $label->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ProductRequest;
use App\Models\Rest\Book;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Book::paginate(10);
        return view('admin.product.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/product');
        }
        Book::create($params);
        session()->flash('success', "Продукт успешно создан");
        return redirect()->route('admin.product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Book $product)
    {
        return view('admin.product.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $product)
    {
        return view('admin.product.product.create', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Book $product)
    {
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/product');
        }
        $product->update($params);
        session()->flash('success', "Продукт '$product->title' успешно изменен");
        return redirect()->route('admin.product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $product)
    {
        Storage::delete($product->image);
        $product->delete();
        return redirect()->back();
    }
}

resources/views/admin/product/product/create.blade.php
@extends('admin.layouts.index')
@section('css')
    <link rel="stylesheet" href="{{asset('css/custom_img.css')}}">
@endsection
@section('content')
    <div class="row">
        <div class="card border-primary mb-3 сщд-12" style="width: 1025px;">
            <div class="card-header bg-primary text-success">Продукт: </div>
            <div class="card-body text-primary">
                <form action="{{ isset($product) ? route('admin.product.update', $product) : route('admin.product.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @if(isset($product))
                        @method('PUT')
                    @endif
                    <div class="row form-group">
                        <div class="col-6">
                            <label>Название книги:</label>
                            <input name="title" type="text" class="form-control" placeholder="Имя книги" value="{{isset($product) ? $product->title : old('title')}}">
                            @include('admin.layouts.valid_error', ['param' => 'title'])
                        </div>
                        <div class="col-6">
                            <label>Автор:</label>
                            <input name="author" type="text" class="form-control" placeholder="Автор" value="{{isset($product) ? $product->author : old('author')}}">
                            @include('admin.layouts.valid_error', ['param' => 'author'])
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-12">
                            <label>Описание:</label>
                            <textarea  name="description" class="form-control"  placeholder="Описание" rows="8">{{isset($product) ? $product->description : old('description')}}</textarea>
                            @include('admin.layouts.valid_error', ['param' => 'description'])
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-6">
                            <label>Категория:</label>
                            <select name="category_id"  onselect="{{isset($product) ? $product->category_id : ''}}{{old('category')}}" class="form-control" id="exampleFormControlSelect1">
                                @foreach(\App\Models\Rest\Category::all() as $category)
                                    <option value="{{$category->id}}" @if(isset($product) && $category->id == $product->category_id) selected @endif>{{$category->name}}</option>
                                @endforeach
                            </select>
                            @include('admin.layouts.valid_error', ['param' => 'category'])

                        </div>
                        <div class="col-6">
                            <label>Издатель:</label>
                            <select name="publisher_id" class="form-control" id="exampleFormControlSelect1">
                                @foreach(\App\Models\Rest\Publisher::all() as $publisher)
                                    <option value="{{$publisher->id}}" @if(isset($product) && $publisher->id == $product->publisher_id) selected @endif>{{$publisher->name}}</option>
                                @endforeach
                            </select>
                            @include('admin.layouts.valid_error', ['param' => 'publisher'])
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-6">
                            <label>Страна:</label>
                            <select name="country_id" onselect="{{isset($product) ? $product->country_id : ''}}" class="form-control" id="exampleFormControlSelect1">
                                @foreach(\App\Models\Rest\Country::all() as $country)
                                    <option value="{{$country->id}}" @if(isset($product) && $country->id == $product->country_id) selected @endif>{{$country->country}}</option>
                                @endforeach
                            </select>
                            @include('admin.layouts.valid_error', ['param' => 'country'])
                        </div>
                        <div class="col-6">
                            <label>Стоимость:</label>
                            <input name="price" type="number" class="form-control" placeholder="Цена" value="{{isset($product) ? $product->price : old('price')}}">
                            @include('admin.layouts.valid_error', ['param' => 'price'])
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <label>Количество на складе:</label>
                            <input name="count" type="number" class="form-control" placeholder="Количество на складе, по умолчанию 0" value="{{isset($product) ? $product->count : old('count')}}">
                            @include('admin.layouts.valid_error', ['param' => 'count'])
                        </div>
                        <div class="col-6">
                            <label>Лейбл:</label>
                            <select name="label_id" onselect="{{isset($product) ? $product->label_id : ''}}" class="form-control" id="label">
                                    <option value="" selected>Без лейбла</option>
                                @foreach(\App\Models\Rest\Label::all() as $label)
                                    <option value="{{$label->id}}" @if(isset($product) && $label->id == $product->label_id) selected @endif>{{$label->name}}</option>
                                @endforeach
                            </select>
                            @include('admin.layouts.valid_error', ['param' => 'label'])
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="custom-file mt-2">
                                <input name="image" type="file" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Выберите Изображения</label>
                                @include('admin.layouts.valid_error', ['param' => 'image'])

                            </div>
                        </div>
                        <div class="col-5 ml-4 mt-4">
                            <input name="available" type="hidden" value="off">
                            <input name="available" {{isset($product) ? ($product->available) ? "checked" : '' : ''}} class="form-check-input" type="checkbox" id="inlineCheckbox1" value="on">
                            <label class="form-check-label" for="inlineCheckbox1">
                                Доступен
                            </label>
                        </div>
                    </div>
                    @if(isset($product))
                        <div class="row">
                            <div class="col-6">
                                <img src="{{\Illuminate\Support\Facades\Storage::url($product->image)}}" class="medium-img ml-5"/>
                            </div>
                        </div>
                    @endif
                    <div class="row mt-3">
                        <div class="col-3">
                            <a href="{{route('admin.product.index')}}" class="form-control btn btn-dark">Все товары</a>
                        </div>
                        <div class="col-3">
                            <button type="submit" class="form-control btn btn-success">@if(isset($product)) Изменить @else Добавить @endif</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
@endsection

resources/views/admin/product/product/index.blade.php
@extends('admin.layouts.index')
@section('css')
    <link rel="stylesheet" href="{{asset('css/custom_img.css')}}">
@endsection
@section('content')
    <div class="row justify-content-end">
        <a href="{{route('admin.product.create')}}" class="btn btn-primary mb-2">Добавить товар</a>
    </div>
    <div class="row">
        <table class="table table-hover">
            <thead class="table-primary">
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Автор</th>
                <th scope="col">На складе</th>
                <th scope="col">Цена</th>
                <th scope="col">Категория</th>
                <th scope="col">Издатель</th>
                <th scope="col">Страна</th>
                <th scope="col">Картинка</th>
                <th scope="col">Доступен</th>
                <th scope="col">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $product)
                <tr class="table-dark">
                    <th>{{$product->title}}</th>
                    <td>{{$product->author}}</td>
                    <td>{{$product->count}}</td>
                    <td>{{$product->price}}</td>
                    <td>{{($product->categories != null) ? $product->categories->name : "null"}}</td>
                    <td>{{$product->publishers->name}}</td>
                    <td>{{$product->countries->country}}</td>
                    <td><img src="{{\Illuminate\Support\Facades\Storage::url($product->image)}}" class="small-img"></td>
                    <td>{{($product->available) ? "Да" : "Нет"}}</td>
                    <td>
                        <form action="{{route('admin.product.destroy', $product)}}" method="POST"class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">delete</button>
                        </form>
                        <a href="{{route('admin.product.edit', $product)}}" class="btn btn-warning">edit</a>
                        <a href="{{route('admin.product.show', $product)}}" class="btn btn-info">overview</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{$products->links()}}
    </div>
@endsection

resources/views/admin/product/product/show.blade.php
@extends('admin.layouts.index')
@section('css')
    <link rel="stylesheet" href="{{asset('css/custom_img.css')}}">
@endsection
@section('content')

    <div class="row">
        <div class="card border-primary mb-3 сщд-12" style="width: 1025px;">
            <div class="card-header bg-primary text-success">Все о продукте: </div>
            <div class="card-body text-primary justify-content-center">
                <div class="card text-white bg-primary mb-3" style="width: 100%;">
                    <div class="card-header">Главная</div>
                    <div class="card-body">
                            <h6 class="card-title">Название книги:</h6>
                            <span class="card-text text-muted">{{$product->title}}</span>
                            <h6 class="card-title mt-2">Описание:</h6>
                            <span class="card-text text-muted">{{$product->description}}</span>
                            <h6 class="card-title mt-2">Автор:</h6>
                            <span class="card-text text-muted">{{$product->author}}</span>
                            <h6 class="card-title mt-2">Жанр:</h6>
                            <span class="card-text text-muted">{{($product->categories != null) ? $product->categories->name : "null"}}</span>
                            <h6 class="card-title mt-2">Цена:</h6>
                            <span class="card-text text-muted">{{$product->price}} грн</span>
                            <h6 class="card-title mt-2">Доступна:</h6>
                            <span class="card-text text-muted">{{($product->available) ? "Да" : "Нет" }}</span>
                            <h6 class="card-title mt-2">Лейблы: </h6>
                            <span class="card-text text-muted">раз два три</span>
                            <h6 class="card-title mt-2">Картинка: </h6>
                            <img src="{{\Illuminate\Support\Facades\Storage::url($product->image)}}" class="big-img">
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection