routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/clear', 'Shop\BasketController@clear');

Route::get('/', 'Shop\MainController@index')->name('shop.index');
Route::get('/product/{product}/show', 'Shop\MainController@show')->name('shop.product.show');

Route::get('/categories', 'Shop\MainController@categories')->name('shop.categories');
Route::get('/category/{category}', 'Shop\MainController@category')->name('shop.category');

Route::get('/filtered', 'Shop\MainController@filter')->name('shop.filter');

Route::group(['middleware' => 'auth'], function (){
    Route::get('/orders', 'Shop\OrderController@index')->name('shop.user.orders');
    Route::post('/product/{product}/rating', 'Shop\RatingController@add')->name('shop.product.rating.add');
});

Route::group(['prefix' => 'basket'], function (){

    Route::get('/', 'Shop\BasketController@index')->name('basket.index');
    Route::post('/{product}/add', 'Shop\BasketController@add')->name('basket.add');
    Route::delete('/{product}/delete', 'Shop\BasketController@delete')->name('basket.delete');

   Route::group(['middleware' => 'order'], function (){
        Route::get('/confirm', 'Shop\BasketController@confirm')->name('basket.confirm');
        Route::put('/processing', 'Shop\BasketController@processing')->name('basket.processing');
   });
});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']],function (){
    Route::get('/', 'Admin\HomeController@index')->name('admin.index');

    Route::get('/orders', 'Admin\OrderController@index')->name('admin.orders');

    Route::group(['prefix' => 'order'], function (){
        Route::get('/{order}', 'Admin\OrderController@show')->name('admin.order');
        Route::get('/{order}/edit', 'Admin\OrderController@edit')->name('admin.order.edit');
        Route::put('/{order}/update', 'Admin\OrderController@update')->name('admin.order.update');
    });

    Route::group(['prefix' => 'users'], function (){
        Route::get('/', 'Admin\UserController@index')->name('admin.users');
        Route::put('/{user}/update', 'Admin\UserController@update')->name('admin.user.update');
        Route::delete('/{user}/destroy', 'Admin\UserController@destroy')->name('admin.user.destroy');
    });

    Route::get('/statistics', 'Admin\StatisticController@index')->name('admin.statistic');

    Route::group(['prefix' => 'product'], function (){
        Route::resource('/label', 'Admin\Product\LabelController')->names('admin.label');
        Route::resource('/category', 'Admin\Product\CategoryController')->names('admin.category');
        Route::resource('/product', 'Admin\Product\ProductController')->names('admin.product');
    });
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Rest/Label.php
<?php

namespace App\Models\Rest;

use Illuminate\Database\Eloquent\Model;

class Label extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/Product/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CategoryRequest;
use App\Models\Rest\Category;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    public function index(){
        $categories = Category::paginate(10);
        return view('admin.product.category.index', compact('categories'));
    }

    public function create(){
        return view('admin.product.category.create');

    }

    public function store(CategoryRequest $request){
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/category');
        }
        Category::create($params);
        session()->flash('success', 'Категория была добавлена');
        return redirect()->route('admin.category.create');
    }

    public function edit(Category $category){
        return view('admin.product.category.create', compact('category'));
    }

    public function update(CategoryRequest $request, Category $category){
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/category');
        }
        $category->update($params);
        session()->flash('warning', 'Категория была обновлена');
        return redirect()->route('admin.category.index');
    }

    public function destroy(Category $category){
        Storage::delete($category->image);
        $category->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/LabelController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\LabelRequest;
use App\Models\Rest\Label;

class LabelController extends Controller
{
    public function index(){
        $labels = Label::paginate(10);
        return view('admin.product.label.index', compact('labels'));
    }

    public function create(){
        return view('admin.product.label.create');
    }

    public function store(LabelRequest $request){
        Label::create($request->all());
        session()->flash('success', 'Лейбл был добавлен');
        return redirect()->route('admin.label.create');
    }

    public function edit(Label $label){
        return view('admin.product.label.create', compact('label'));
    }

    public function update(LabelRequest $request, Label $label){
        $label->update($request->all());
        session()->flash('warning', 'Лейбл был изменен');
        return redirect()->route('admin.label.index');
    }

    public function destroy(Label $label){
        $label->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ProductRequest;
use App\Models\Rest\Book;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Book::paginate(10);
        return view('admin.product.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/product');
        }
        Book::create($params);
        session()->flash('success', "Продукт успешно создан");
        return redirect()->route('admin.product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Book $product)
    {
        return view('admin.product.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $product)
    {
        return view('admin.product.product.create', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Book $product)
    {
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/product');
        }
        $product->update($params);
        session()->flash('success', "Продукт '$product->title' успешно изменен");
        return redirect()->route('admin.product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $product)
    {
        Storage::delete($product->image);
        $product->delete();
        return redirect()->back();
    }
}

resources/views/admin/product/label/create.blade.php
@extends('admin.layouts.index')

@section('content')
    <div class="row">

        <div class="card border-primary mb-3 сщд-12" style="width: 525px;">
            <div class="card-header bg-primary text-success">Новый лейбл</div>
            <div class="card-body text-primary">
                <form action="{{ isset($label) ? route('admin.label.update', $label) : route('admin.label.store')}}" method="POST">
                    @csrf
                    @if(isset($label))
                        @method('PUT')
                    @endif
                    <div class="row">
                        <div class="col-9">
                            <input name="name" type="text" class="form-control" placeholder="Лейбл" value="@if(isset($label)){{$label->name}}@endif{{old('name')}}">
                            @include('admin.layouts.valid_error', ['param' => 'name'])
                        </div>
                        <div class="col-9 mt-3">
                            <input name="color" type="color" class="form-control" placeholder="Цвет" value="@if(isset($label)){{$label->color}}@endif{{old('color')}}">
                            @include('admin.layouts.valid_error', ['param' => 'name'])
                        </div>
                        <div class="col-3 mt-3">
                            <button type="submit" class="form-control btn btn-success">@if(isset($label)) Изменить @else Добавить @endif</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
@endsection

resources/views/admin/product/label/index.blade.php
@extends('admin.layouts.index')

@section('content')
    <div class="row justify-content-end">
        <a href="{{route('admin.label.create')}}" class="btn btn-primary mb-2">Добавить лейбл</a>
    </div>
    <div class="row">
        <table class="table table-hover">
            <thead class="table-primary">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Название</th>
                <th scope="col">Цвет</th>
                <th scope="col">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($labels as $label)
                <tr class="table-dark">
                    <th>{{$label->id}}</th>
                    <td>{{$label->name}}</td>
                    <td><div style="height: 30px; width: 30px; background: {{$label->color}}"></div></td>
                    <td>
                        <form action="{{route('admin.label.destroy', $label)}}" method="POST"class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">delete</button>
                        </form>
                        <a href="{{route('admin.label.edit', $label)}}" class="btn btn-warning">edit</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{$labels->links()}}
    </div>
@endsection