routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/clear', 'Shop\BasketController@clear');

Route::get('/', 'Shop\MainController@index')->name('shop.index');
Route::get('/product/{product}/show', 'Shop\MainController@show')->name('shop.product.show');

Route::get('/categories', 'Shop\MainController@categories')->name('shop.categories');
Route::get('/category/{category}', 'Shop\MainController@category')->name('shop.category');

Route::get('/filtered', 'Shop\MainController@filter')->name('shop.filter');

Route::group(['middleware' => 'auth'], function (){
    Route::get('/orders', 'Shop\OrderController@index')->name('shop.user.orders');
    Route::post('/product/{product}/rating', 'Shop\RatingController@add')->name('shop.product.rating.add');
});

Route::group(['prefix' => 'basket'], function (){

    Route::get('/', 'Shop\BasketController@index')->name('basket.index');
    Route::post('/{product}/add', 'Shop\BasketController@add')->name('basket.add');
    Route::delete('/{product}/delete', 'Shop\BasketController@delete')->name('basket.delete');

   Route::group(['middleware' => 'order'], function (){
        Route::get('/confirm', 'Shop\BasketController@confirm')->name('basket.confirm');
        Route::put('/processing', 'Shop\BasketController@processing')->name('basket.processing');
   });
});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']],function (){
    Route::get('/', 'Admin\HomeController@index')->name('admin.index');

    Route::get('/orders', 'Admin\OrderController@index')->name('admin.orders');

    Route::group(['prefix' => 'order'], function (){
        Route::get('/{order}', 'Admin\OrderController@show')->name('admin.order');
        Route::get('/{order}/edit', 'Admin\OrderController@edit')->name('admin.order.edit');
        Route::put('/{order}/update', 'Admin\OrderController@update')->name('admin.order.update');
    });

    Route::group(['prefix' => 'users'], function (){
        Route::get('/', 'Admin\UserController@index')->name('admin.users');
        Route::put('/{user}/update', 'Admin\UserController@update')->name('admin.user.update');
        Route::delete('/{user}/destroy', 'Admin\UserController@destroy')->name('admin.user.destroy');
    });

    Route::get('/statistics', 'Admin\StatisticController@index')->name('admin.statistic');

    Route::group(['prefix' => 'product'], function (){
        Route::resource('/label', 'Admin\Product\LabelController')->names('admin.label');
        Route::resource('/category', 'Admin\Product\CategoryController')->names('admin.category');
        Route::resource('/product', 'Admin\Product\ProductController')->names('admin.product');
    });
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Rest/Category.php
<?php

namespace App\Models\Rest;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    protected $table = 'categories';

    public function products(){
        return $this->hasMany(Book::class);
    }
    public function  getRouteKeyName()
    {
        return 'name';
    }
}

app/Http/Controllers/Admin/Product/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CategoryRequest;
use App\Models\Rest\Category;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    public function index(){
        $categories = Category::paginate(10);
        return view('admin.product.category.index', compact('categories'));
    }

    public function create(){
        return view('admin.product.category.create');

    }

    public function store(CategoryRequest $request){
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/category');
        }
        Category::create($params);
        session()->flash('success', 'Категория была добавлена');
        return redirect()->route('admin.category.create');
    }

    public function edit(Category $category){
        return view('admin.product.category.create', compact('category'));
    }

    public function update(CategoryRequest $request, Category $category){
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/category');
        }
        $category->update($params);
        session()->flash('warning', 'Категория была обновлена');
        return redirect()->route('admin.category.index');
    }

    public function destroy(Category $category){
        Storage::delete($category->image);
        $category->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/LabelController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\LabelRequest;
use App\Models\Rest\Label;

class LabelController extends Controller
{
    public function index(){
        $labels = Label::paginate(10);
        return view('admin.product.label.index', compact('labels'));
    }

    public function create(){
        return view('admin.product.label.create');
    }

    public function store(LabelRequest $request){
        Label::create($request->all());
        session()->flash('success', 'Лейбл был добавлен');
        return redirect()->route('admin.label.create');
    }

    public function edit(Label $label){
        return view('admin.product.label.create', compact('label'));
    }

    public function update(LabelRequest $request, Label $label){
        $label->update($request->all());
        session()->flash('warning', 'Лейбл был изменен');
        return redirect()->route('admin.label.index');
    }

    public function destroy(Label $label){
        $label->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ProductRequest;
use App\Models\Rest\Book;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Book::paginate(10);
        return view('admin.product.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/product');
        }
        Book::create($params);
        session()->flash('success', "Продукт успешно создан");
        return redirect()->route('admin.product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Book $product)
    {
        return view('admin.product.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $product)
    {
        return view('admin.product.product.create', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Book $product)
    {
        $params = $request->all();
        if(isset($params['image'])){
            $params['image'] = $request->file('image')->store('public/product');
        }
        $product->update($params);
        session()->flash('success', "Продукт '$product->title' успешно изменен");
        return redirect()->route('admin.product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $product)
    {
        Storage::delete($product->image);
        $product->delete();
        return redirect()->back();
    }
}

resources/views/admin/product/category/create.blade.php
@extends('admin.layouts.index')
@section('css')
    <link rel="stylesheet" href="{{asset('css/custom_img.css')}}">
@endsection

@section('content')

    <div class="row">

        <div class="card border-primary mb-3 сщд-12" style="width: 525px;">
            <div class="card-header bg-primary text-success">Новая категория</div>
            <div class="card-body text-primary">
                <form action="{{ isset($category) ? route('admin.category.update', $category) : route('admin.category.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @if(isset($category))
                        @method('PUT')
                    @endif
                    <div class="row">
                        <div class="col-9">
                            <input name="name" type="text" class="form-control" placeholder="Категория" value="@if(isset($category)){{$category->name}}@endif{{old('name')}}">
                            @include('admin.layouts.valid_error', ['param' => 'name'])
                            <div class="custom-file mt-2">
                                <input name="image" type="file" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Выберите Изображения</label>
                            </div>
                            @include('admin.layouts.valid_error', ['param' => 'image'])
                        </div>
                        <div class="col-3">
                            <button type="submit" class="form-control btn btn-success">@if(isset($category)) Изменить @else Добавить @endif</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    @if(isset($category))
    <img src="{{\Illuminate\Support\Facades\Storage::url($category->image)}}" class="medium-img ml-5"/>
    @endif
</div>
@endsection

resources/views/admin/product/category/index.blade.php
@extends('admin.layouts.index')
@section('css')
    <link rel="stylesheet" href="{{asset('css/custom_img.css')}}">
@endsection
@section('content')
    <div class="row justify-content-end">
        <a href="{{route('admin.category.create')}}" class="btn btn-primary mb-2">Добавить категорию</a>
    </div>
    <div class="row">
        <table class="table table-hover">
            <thead class="table-primary">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Категория</th>
                <th scope="col">картинка</th>
                <th scope="col">Действия</th>
            </tr>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr class="table-dark">
                        <th>{{$category->id}}</th>
                        <td>{{$category->name}}</td>
                        <td><img src="{{\Illuminate\Support\Facades\Storage::url($category->image)}}" class="small-img"></td>
                        <td>
                            <form action="{{route('admin.category.destroy', $category)}}" method="POST"class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">delete</button>
                            </form>
                            <a href="{{route('admin.category.edit', $category)}}" class="btn btn-warning">edit</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{$categories->links()}}
    </div>
@endsection